Adding gpu type
run-ai/runai-cli pull request #107
Opened 2021-03-17 13:58 UTC by moshe-kabala

2021-03-17 14:34 UTC, moshe-kabala commented
I added a function called SetLabel to define an index label on a string, but I do not use it. I think it might be useful in the feature. If you do not agree let me know and I will remove it

2021-03-21 15:11 UTC, yodarshafrir1 requested changes
please see my notes and attach a screenshot

2021-03-21 15:11 UTC, yodarshafrir1 commented on pkg/prometheus/helpers.go
> +func SetLabel(str *string, label string ,m MetricResultsByQueryName, key string) error {
why do we need this?

2021-03-21 15:11 UTC, yodarshafrir1 commented on pkg/nodes/node_info.go
> +	nodeResStatus.GpuType = ni.Node.Labels["nvidia.com/gpu.product"]
if label not found please set a proper message

2021-03-22 15:42 UTC, moshe-kabala commented on pkg/nodes/node_info.go
> +	nodeResStatus.GpuType = ni.Node.Labels["nvidia.com/gpu.product"]
in the field itself? which text? (Not found or - )
by the there is a case of not a GPU node

2021-03-25 08:41 UTC, yodarshafrir1 requested changes

2021-03-25 08:41 UTC, yodarshafrir1 commented on pkg/helpers/node_resources_status_helpers.go
> +		Type: 		 nrs.GpuType,
please rename to `GpuType`

2021-03-25 08:41 UTC, yodarshafrir1 commented on pkg/types/node.go
> +	Type        string  `title:"TYPE" def:"-"`
Please rename to `GpuType`

2021-03-25 08:59 UTC, yodarshafrir1 approved these changes

2021-03-25 09:01 UTC, merged