adding runai cli command annotation
run-ai/runai-cli pull request #109
Opened 2021-04-04 08:57 UTC by moshe-kabala

2021-04-13 07:45 UTC, yodarshafrir1 requested changes

2021-04-13 07:45 UTC, yodarshafrir1 commented on charts/mpijob/templates/mpi-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
why did you add it to both mpijob annotation and pod annotation?

2021-04-13 07:45 UTC, yodarshafrir1 commented on charts/runai/templates/runai-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
why did you add it to both runaijob annotation and pod annotation?

2021-04-13 07:45 UTC, yodarshafrir1 commented on cmd/job/describe_job.go
> +func getCommandLine(job trainer.TrainingJob) ( commandLine string ) {
if no command line write `N/A` or something similiar

2021-04-13 07:45 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +	RunaiCliCommand		string   `yaml:"runaiCliCommand,omitempty"`
`cliCommand`

2021-04-13 07:45 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +	submitArgs.addRunaiCliCommand()
you are calling this method from all the job kinds.
better use a common method like: `addCommonSubmit` and from this method call `addCommonFlags` and `addRunaiCliCommand`

2021-04-13 07:45 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +func(submitArgs *submitArgs) addRunaiCliCommand() {
why do we need the runai in the name?

2021-04-13 07:46 UTC, yodarshafrir1 commented on charts/mpijob/templates/mpi-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
better stick with job's annotation

2021-04-18 18:29 UTC, moshe-kabala commented on charts/mpijob/templates/mpi-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
In the scheduler, I extract from the pod but in the researcher UI from the job.

2021-04-18 18:29 UTC, moshe-kabala commented on charts/runai/templates/runai-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
In the scheduler, I extract from the pod but in the researcher UI from the job.

2021-04-18 18:33 UTC, moshe-kabala commented on cmd/job/submit/submit.go
> +func(submitArgs *submitArgs) addRunaiCliCommand() {
fixed

2021-04-18 18:33 UTC, moshe-kabala commented on cmd/job/submit/submit_mpi.go
> +	submitArgs.addRunaiCliCommand()
fixed

2021-04-18 18:38 UTC, moshe-kabala commented on cmd/job/submit/submit.go
> +	RunaiCliCommand		string   `yaml:"runaiCliCommand,omitempty"`
fixed

2021-04-18 18:38 UTC, moshe-kabala commented on cmd/job/describe_job.go
> +func getCommandLine(job trainer.TrainingJob) ( commandLine string ) {
fixed

2021-04-22 07:41 UTC, yodarshafrir1 commented on charts/mpijob/templates/mpi-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
why not do the same in both?

2021-04-22 07:45 UTC, yodarshafrir1 commented
Instead of putting the same label on both annotations of job and pods, can we stick to one of them? (the job is better)

2021-04-25 07:36 UTC, moshe-kabala commented on charts/mpijob/templates/mpi-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
As agreed I will remain with the 'job' annotation

2021-04-25 07:36 UTC, moshe-kabala commented on charts/runai/templates/runai-job.yaml
> +    runai-cli-command: {{ .Values.runaiCliCommand | quote }}
As agreed I will remain with the 'job' annotation

2021-05-06 05:27 UTC, omer-dayan reviewed
Liked it,
Please notice its super important to save the CLI Command as BASE64 and not raw text

Also: What about the default template? The CLI command may be mis-leading by its own

2021-05-06 05:27 UTC, omer-dayan commented on cmd/job/describe_job.go
> +func stringWithDefault(str string, def string) string {
Its better call "getStringOrDefault", because "with" is not really what we do

2021-05-06 05:27 UTC, omer-dayan commented on cmd/job/describe_job.go
> +func stringWithDefault(str string, def string) string {
Do we really want seperate function for this?

2021-05-06 05:27 UTC, omer-dayan commented on cmd/job/submit/submit.go
> +	CliCommand		     string  `yaml:"cliCommand,omitempty"`
Why is it public if its only used within this package?

2021-05-06 05:27 UTC, omer-dayan commented on cmd/job/submit/submit.go
> +	submitArgs.CliCommand = strings.Join( os.Args , " ")
NO NO its bad to save it that way, attacker can interfere our YAML file

It should be saved as BASE64

2021-05-06 05:27 UTC, omer-dayan commented on cmd/util/gpu.go
> +	CliCommand        				   = "runai-cli-command"
Its not related to GPU, move it to consts.go

2021-05-06 07:18 UTC, moshe-kabala commented on cmd/job/describe_job.go
> +func stringWithDefault(str string, def string) string {
deleted

2021-05-06 07:19 UTC, moshe-kabala commented on cmd/job/submit/submit.go
> +	CliCommand		     string  `yaml:"cliCommand,omitempty"`
It private now

2021-05-06 07:20 UTC, moshe-kabala commented on cmd/util/gpu.go
> +	CliCommand        				   = "runai-cli-command"
moved to the const file

2021-05-06 09:25 UTC, moshe-kabala commented on cmd/job/submit/submit.go
> +	submitArgs.CliCommand = strings.Join( os.Args , " ")
It is OK we are using  quote (in the template)

2021-05-06 13:51 UTC, omer-dayan commented on cmd/job/submit/submit.go
> +	submitArgs.CliCommand = strings.Join( os.Args , " ")
Yes its doing escaping but we may lose data when escaping, For example: 

The command : "runai submit -i ubuntu -g 0 --dry-run -- echo \n\t hello"
Becomes : "runai submit -i ubuntu -g 0 --dry-run -- echo nt hello"

2021-05-06 15:02 UTC, omer-dayan approved these changes

2021-05-06 15:07 UTC, merged