"inference" flag now not hidden
run-ai/runai-cli pull request #127
Opened 2021-05-03 11:02 UTC by natasharomm

2021-05-05 15:11 UTC, yodarshafrir1 requested changes

2021-05-05 15:11 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +	Inference           *bool  `yaml:"inference,omitempty"`
When adding the flag to this file you actually added this flag to MPI jobs as well. we don't support Inference for MPI jobs. let's move it back to the old file

2021-05-06 07:18 UTC, natasharomm commented on cmd/job/submit/submit.go
> +	Inference           *bool  `yaml:"inference,omitempty"`
fixedd

2021-05-06 14:21 UTC, yodarshafrir1 approved these changes

2021-05-06 14:29 UTC, merged