Added sorting job list by name then by project
run-ai/runai-cli pull request #128
Opened 2021-05-03 13:33 UTC by natasharomm

2021-05-05 15:09 UTC, yodarshafrir1 requested changes

2021-05-05 15:09 UTC, yodarshafrir1 commented on cmd/trainer/trainer.go
> +func (this orderedTrainingJobByName) Len() int {
can you name it with a different name rather than `this`, we don't use it in golang

2021-05-05 15:09 UTC, yodarshafrir1 commented on cmd/trainer/trainer.go
> +	for _, v := range jobList {
`job` instead of `v`?

2021-05-05 15:09 UTC, yodarshafrir1 commented on cmd/trainer/trainer.go
> +	newJoblist := make(orderedTrainingJobByProject	, 0, len(jobList))
```
var  orderedTrainingJobByProject []TrainingJob
```

2021-05-05 15:09 UTC, yodarshafrir1 commented on cmd/trainer/trainer.go
> +func (this orderedTrainingJobByName) Len() int {
You created a new object with methods, I'd move it to a different file, it's not related to `trainer.go`

2021-05-05 15:09 UTC, yodarshafrir1 commented on cmd/trainer/trainer.go
> +	return []TrainingJob(newJoblist)
can you return `newJoblist` ? why do we need to create it again?

2021-05-06 07:25 UTC, natasharomm commented on cmd/trainer/trainer.go
> +func (this orderedTrainingJobByName) Len() int {
renamed "this".
I don't agree about the file - there are two other "sorting" functions of training jobs in this file and I wanted to keep them together.

2021-05-06 07:25 UTC, natasharomm commented on cmd/trainer/trainer.go
> +	for _, v := range jobList {
fixed

2021-05-06 07:28 UTC, natasharomm commented on cmd/trainer/trainer.go
> +	newJoblist := make(orderedTrainingJobByProject	, 0, len(jobList))
var newJoblist orderedTrainingJobByName
(orderedTrainingJobByName is the type)

2021-05-06 07:29 UTC, natasharomm commented on cmd/trainer/trainer.go
> +	return []TrainingJob(newJoblist)
fixed

2021-05-06 15:08 UTC, yodarshafrir1 approved these changes

2021-05-06 15:13 UTC, merged