reuse Project struct
run-ai/runai-cli pull request #130
Opened 2021-05-05 11:30 UTC by oferla

2021-05-20 09:13 UTC, oferla commented on cmd/dashboard_helper.go
> +	ep, err := client.CoreV1().Endpoints(namespace).Get(context.TODO(), name, metav1.GetOptions{})
You can ignore those changes, they are related to version upgrade of go-client.

2021-05-20 09:15 UTC, oferla commented on cmd/job/delete/delete.go
> +			rs := rsrch_client.NewRsrchClient(restConfig, rsrch_client.DeleteJobMinVersion)
we receive rs object only if RS exist, support versioning, and has a version which supports delete job REST API.

2021-06-03 00:02 UTC, omer-dayan requested changes
A few questions about the PR solution (see my answer inline)

1) 
![image](https://user-images.githubusercontent.com/10087174/120566302-9f401100-c417-11eb-86c6-5cd4c9b62c7e.png)
What does this files changes related?
### Answer

2) What happens if we have a client like KCL which have older cluster and dont have yet the RS? Do we want to support the old fashion requests? I didnt see you done it in the delete workflow
### Answer 
We nad a dis cussion about it, and the decision was that as for *now*, in case of any failure in contacting the RS, either due to technical issue or because RS has not been upgraded to support the CLI queries, the CLI will invoke the RS method directly. When we'll have significant number of customers that have CLI and RS synced, we may consider to remove the direct calls. When we get to that bridge we'll cross it. For now the flow is REST call -> failure -> direct call. Here is the code:
```
			rs := rsrch_client.NewRsrchClient(restConfig, rsrch_client.DeleteJobMinVersion)
			if rs != nil {
				//
				//   RS can serve the request, so send it to RS
				//
				deleteJobsStatus, err = rs.JobDelete(context.TODO(), jobsToDelete)
			} else {
				log.Infof("researcher-service cannot serve the request, use in-house CLI for job delete")

				clientSet, err := rsrch_cs.NewCliClientFromConfig(restConfig)
				if err != nil {
					log.Errorf("Failed to create clientSet for in-house CLI job delete: %v", err.Error())
					return
				}

				deleteJobsStatus = clientSet.DeleteJobs(context.TODO(), jobsToDelete)
			}
```
The "else" is the direct call, it is invoked if contacting the RS failed for any reason (including versioning mismatch).

3) Do we want to have a RS package in the CLI only so we can have the common objects?
### Answer
Originally, we added the RS package in order for the CLI to reuse the structures and types of RS and to avoid code duplications b/w them. Later on, when the issue of CLI vs old RS came up, we used it also for the "direct call". So instead of leaving all the old code inside CLI, we simply benefit the RS package for direct calling its functions. When/if we decide to remove the "direct call" we will still leave the package for the original purpose.

2021-06-05 21:46 UTC, omer-dayan reviewed
Reviewed almost everything, stoped in the middle because I miss something. Read my comments and tell me what you think

2021-06-05 21:46 UTC, omer-dayan commented on cmd/job/delete/delete.go
> +					}
I am sorry. But I miss something. 

You said that if the RS does not exist then you run the original flow. 
But all I see here that when you run delete command you use only RS flow. Furthermore, you deleted all the logic of deletion from 'workflow.go' (-> submit.go)

2021-06-05 21:46 UTC, omer-dayan commented on cmd/util/util.go
> +	return namespace[len(constants.RunaiNsProjectPrefix):]
Just like that? 
Without checking the existence of the 'runai-'? You actually made a really good function for that (IsProjectNamespace)

I am just so sure that people in the future will use this function without checking the input by themself.
"ToProject" its just such a inviting name

2021-06-05 21:46 UTC, omer-dayan commented on cmd/project/completion.go
> +	projects, _, err := PrepareListOfProjects(restConfig, false /*do not include deleted projects*/)
Also here, someone who does not upgraded the cluster to the version with RS will lose this feature

2021-06-06 07:43 UTC, oferla commented on cmd/job/delete/delete.go
> +					}
Sent you a demo and will explain to you in the office.

2021-06-06 07:43 UTC, oferla commented on cmd/project/completion.go
> +	projects, _, err := PrepareListOfProjects(restConfig, false /*do not include deleted projects*/)
Same here, demo sent explanation in the office :-)

2021-06-12 17:03 UTC, omer-dayan approved these changes

2021-06-12 18:43 UTC, merged