Run 1813 allow nfs volume mount
run-ai/runai-cli pull request #169
Opened 2021-08-08 12:03 UTC by natasharomm

2021-08-08 13:01 UTC, gshaibi requested changes

2021-08-08 13:01 UTC, gshaibi commented on cmd/job/submit/volume_handler.go
> +		joinednfsParams = fmt.Sprintf("%s,%s", joinednfsParams, "runai-nfs-volume")
Following the last commit, you won't need that anymore

2021-08-08 13:01 UTC, gshaibi commented on cmd/job/submit/volume_handler.go
> +func handleNfsVolumes(args *submitArgs) error {
So that function actually becomes validate only right?

2021-08-08 13:13 UTC, gshaibi submitted a review, later dismissed

2021-08-08 13:14 UTC, gshaibi commented
Thanks for teaching me 🥇

2021-08-09 11:20 UTC, gshaibi requested changes
Awesome. So we don't support nfs and local host together right?

2021-08-09 11:20 UTC, gshaibi commented on cmd/job/submit/submit.go
> +	flagSet.StringArrayVarP(&(submitArgs.Volumes), "volume", "v", []string{}, "Volumes to mount into the container. If volume is not mounted to host, use in conjunction with --nfs-server. Syntax: 'HostP
maybe, not a must.
```suggestion
	flagSet.StringArrayVarP(&(submitArgs.Volumes), "volume", "v", []string{}, "Volumes to mount into the container. If volume is not mounted on the host, use in conjunction with --nfs-server. Syntax: 'HostPath:ContainerPath:AccessMode[optional]'")
```

2021-08-09 11:20 UTC, gshaibi commented on cmd/job/submit/submit.go
> +	flagSet.StringVar(&(submitArgs.NfsServer), "nfs-server", "", "Mount volumes from this server . Use in conjunction with the -v flag.")
```suggestion
	flagSet.StringVar(&(submitArgs.NfsServer), "nfs-server", "", "Mount volumes from this server. Use in conjunction with the -v flag.")
```

2021-08-09 11:23 UTC, natasharomm commented on cmd/job/submit/submit.go
> +	flagSet.StringArrayVarP(&(submitArgs.Volumes), "volume", "v", []string{}, "Volumes to mount into the container. If volume is not mounted to host, use in conjunction with --nfs-server. Syntax: 'HostP
Yaron (as a PM representative) sent me the text, I'm not arguing

2021-08-09 11:24 UTC, gshaibi approved these changes

2021-08-09 11:47 UTC, itayvallach approved these changes

2021-08-09 11:48 UTC, merged