RUN-2096/unclear-no-projects-message
run-ai/runai-cli pull request #189
Opened 2021-09-20 10:07 UTC by oferla

2021-09-22 20:05 UTC, itayvallach requested changes

2021-09-22 20:05 UTC, itayvallach commented on cmd/util/util.go
> +		return "", fmt.Errorf("Project %s does not exist. Run '%s list project' to view all avaliable projects", project, config.CLIName)
typo in "available"

2021-09-22 20:05 UTC, itayvallach commented on cmd/job/submit/submit_template_loader.go
> +		return nil, fmt.Errorf("You are not permitted to view any project. Contact your site administrator for further details.")
any project***s***.  Also I would drop the word "site" in this message.

2021-09-23 06:12 UTC, oferla commented on cmd/util/util.go
> +		return "", fmt.Errorf("Project %s does not exist. Run '%s list project' to view all avaliable projects", project, config.CLIName)
I hope you noticed it was in the original message as well :-)

2021-09-23 06:20 UTC, itayvallach approved these changes

2021-09-23 07:52 UTC, merged