Removed dependency in kubectl and helm
run-ai/runai-cli pull request #209
Opened 2021-12-15 15:03 UTC by omeryahud

`runai` cli tool will now template and submit jobs directly against
kube-api instead of templating with `helm` and submitting with `kubectl`

2021-12-16 15:46 UTC, omeryahud commented
This is ready for review, will be tested using the existing QA E2E test suite

2021-12-19 19:58 UTC, oferla requested changes

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +	split := strings.Split(pvcStr, ":")
better call it "parts"... split is the action not the result.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +	splits := strings.Split(pvcVolStr, ":")
We moved from "split" to "splits"?!! not even sure it's correct English... parts. much better name.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +	}
if you sure len(splits) is either 3 or 4 no need for the "else if" just "else".
if you're not sure add "else" with error message

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +func portForward(localAddresses, ports []string, jobName, namespace string,
Is the code of this function copied from somewhere (like kubectl?) I could have hoped there is a standard library function for this... otherwise not sure this is the place for it. better move to util of some sort. seems too low level for here.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +	}
Just to verify: are you sure you're using the same config as the CLI itself?

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +func coreV1TypeMeta(obj runtime.Object) metav1.TypeMeta {
Again not sure that all the typing functions should be here. would move them to a more isolated places than this file, which should include the submit business logic.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +			Resource: pluralize.NewClient().Pluralize(strings.ToLower(gvk.Kind), 2, false),
2? maybe constant whose name can explain what is this miraculous 2?

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +func getPodLogs(pod *v1.Pod, kubeClient *client.Client) (string, error) {
not the right place for this function (I think it is not even being used in this source)

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit.go
> +func mergeStringMaps(a, b map[string]string) map[string]string {
again - looking at this source file, I an not seeing this function used. maybe the browser find operation is malfunctioning... could be. but if not used better be removed and if used better be moved.
ושלמה ארצי אפילו יכול להלחין את המשפט הזה

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_mpi.go
> +const (
worth adding comment explaining the two numeric constants.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +			if len(submitArgs.Image) == 0 {
isn't it too early to test this? I hope that in here the submitArgs already have all the defaults from jobsettings and user/global templates merged to it.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +	slice := strings.Split(portStr, ":")
I still think parts is better 🥇

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +			ingress.Spec.Rules[0].HTTP.Paths = append(ingress.Spec.Rules[0].HTTP.Paths, *ingressPort)
Everything is squeezed to rule 0? no typo here?

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +	split := strings.Split(portStr, ":")
finally you had the slices which is better than split, and now you're back to split?!!?! 👎

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +	portValue := int32((&portIntStr).IntValue())
I hope that go has a better way to cover port from string to int32...

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +	portValue := int32((&portIntStr).IntValue())
same comment again.

2021-12-19 19:58 UTC, oferla commented on cmd/job/submit/submit_runai.go
> +	}
Maybe a one lines comment explaining the logic here?

2021-12-19 19:58 UTC, oferla commented on pkg/portforward/portforward.go
> +	hostIP := strings.TrimLeft(req.RestConfig.Host, "htps:/")
Only because it's 11pm I really did google on "htps" but since it did not find anything related I assume this is a typo and should be https:, but maybe you'll surprise me tomorrow...

2021-12-19 19:58 UTC, oferla commented on pkg/portforward/portforward.go
> +		&url.URL{Scheme: "https", Path: path, Host: hostIP})
...or maybe not.

2021-12-19 19:58 UTC, oferla commented on pkg/workflow/submit.go
> +	//labels[kubectl.JOB_CONFIG_LABEL_KEY] = kubectl.JOB_CONFIG_LABEL_VALUES
Dead code?

2021-12-20 09:07 UTC, omeryahud commented on cmd/job/submit/submit.go
> +	}
len(*slice*) can also be 2:
`--pvc stringArray      Mount a persistent volume. Syntax: 'StorageClass[optional]:Size:ContainerMountPath:ro[optional]'`

2021-12-20 09:08 UTC, omeryahud commented on cmd/job/submit/submit.go
> +	}
But something else looks strange to me, I'll look into it

2021-12-20 09:09 UTC, omeryahud commented on cmd/job/submit/submit.go
> +	}
Never mind, it cannot be 2, only 3 or 4

2021-12-20 09:11 UTC, omeryahud commented on cmd/job/submit/submit.go
> +func portForward(localAddresses, ports []string, jobName, namespace string,
It is not copied from `kubectl`, the function `portforward.PortForwardAPod` uses the k8s libraries to perform port forwarding

2021-12-20 09:14 UTC, omeryahud commented on cmd/job/submit/submit.go
> +	}
Yes, any caller to `client.GetRestConfig` will be configured to access to same cluster context

2021-12-20 09:45 UTC, omeryahud commented on cmd/job/submit/submit.go
> +func coreV1TypeMeta(obj runtime.Object) metav1.TypeMeta {
Done, created `*_resources.go` files for each job

2021-12-20 09:47 UTC, omeryahud commented on cmd/job/submit/submit.go
> +func getPodLogs(pod *v1.Pod, kubeClient *client.Client) (string, error) {
It is being used, but I agree that I can move it to a different place

2021-12-20 10:01 UTC, omeryahud commented on cmd/job/submit/submit_mpi.go
> +const (
I wish I knew what `SlotsPerWorker` means

2021-12-20 10:03 UTC, omeryahud commented on cmd/job/submit/submit_runai.go
> +			if len(submitArgs.Image) == 0 {
Yes, you can see here that templates are handled prior to this check https://github.com/run-ai/runai-cli/pull/209/files/8440bf91cf5b6a43e70a0e761bc4f226dd800e4b#diff-99a1c3ae9f63e0a4684aa8935157ab4b8ad767323d9d0a07194f9ee4c97573bcR91

2021-12-20 10:05 UTC, omeryahud commented on cmd/job/submit/submit_runai.go
> +			ingress.Spec.Rules[0].HTTP.Paths = append(ingress.Spec.Rules[0].HTTP.Paths, *ingressPort)
No typo, everything is in the same rule https://github.com/run-ai/runai-cli/pull/209/files/8440bf91cf5b6a43e70a0e761bc4f226dd800e4b?authenticity_token=IKGx%2F8eYDFbF54%2FvwKQRfniopfNCXScSzH9uOfqM8F%2FEuvrCHRrlrLS5dpSeoO3Z3XDskH54gEiEBKG5Jhq20A%3D%3D&file-filters%5B%5D=.go&file-filters%5B%5D=.mod&file-filters%5B%5D=.sum&file-filters%5B%5D=.lock&file-filters%5B%5D=.md&file-filters%5B%5D=.tpl&file-filters%5B%5D=.yaml&file-filters%5B%5D=dotfile#diff-99e59f58a53e00378ebf58f41338f7c7f9bba222673e8fa6f0a42b852f6bc32aL19

2021-12-20 10:08 UTC, omeryahud commented on cmd/job/submit/submit_runai.go
> +	portValue := int32((&portIntStr).IntValue())
This is not a go thing, it's a k8s thing, the API defines a struct called `IntOrString`, so no better way for that

2021-12-20 10:08 UTC, omeryahud commented on cmd/job/submit/submit_runai.go
> +	portValue := int32((&portIntStr).IntValue())
Same as above

2021-12-20 10:14 UTC, omeryahud commented on cmd/job/submit/submit_runai.go
> +	}
Done, added a comment at the top of the function

2021-12-20 10:52 UTC, oferla commented on cmd/job/submit/submit.go
> +func portForward(localAddresses, ports []string, jobName, namespace string,
I think it should not reside in submit.go, but this is outside the scope for this task we can do it somewhere else. Should be a file handling port forwarding, waiting for pod to run and then log, etc... it is all outside the scope for submit.go, but not mandatory for this PR if it is too much work.

2022-01-03 09:34 UTC, itayvallach approved these changes

2022-01-03 09:54 UTC, oferla approved these changes

2022-01-03 09:54 UTC, itayvallach approved these changes

2022-01-03 09:55 UTC, merged