RUN-967 - adding table interface to utils, some functions to run a query in prom and adding (nornmolize) the top node
run-ai/runai-cli pull request #22
Opened 2020-09-24 06:35 UTC by moshe-kabala

2020-10-07 08:35 UTC, yodarshafrir1 requested changes
Reviewed, please see my notes.
Also please do the following:
1. Remove all the functions from the types.go file
2. Remove all irrelevant `todo`s along the code.
3. Check the output of this command with fractional GPUs jobs, and then without GPU nodes at all (you can just disable the nvidia-device-plugin, I can help you with that).
4. Please rebase

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +		getFunc();
did you mean to use goroutine?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	var mux sync.Mutex
why do you need mutex here? they all update a different value

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +		// todo: check the metric type
do we want this todo here?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +				return nil, fmt.Errorf("[Prometheos] Not found an 'itemID' (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
This error will later be shown to the user.
the user has no idea what is `itemID`. let's rephrase it

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +			if !created {
can it already be created? if so please explain

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +	// if need to hide the filed
filed -> field

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +//// helpers
let's extract to a new file called helpers?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +	return items, nil
if it never returns an error why do we want to have this in the type of the return value

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +func UnwrapValuePtr(ft reflect.Value) *reflect.Value {
why ft?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +func UnwrapTypePtr(ft reflect.Type) reflect.Type {
why ft

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +		// todo
todo what?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table.go
> +func getNesstedVal(t reflect.Value, path []string) (val *reflect.Value) {
why t

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table_tes.go
> +func RunTableExampleTes() {
Please rename this and task, you are missing a `t` in `test`

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/ui/table_tes.go
> +func RunTableExampleTes() {
please use the golang test framework so it will run in ci as well?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/util/cache.go
> +	c.mux.Lock()
why is the mutex needed?

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/util/cache.go
> +	c.mux.Lock()
why is the mutex needed

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/util/cache.go
> +	mux sync.Mutex
please rename to mutex

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/util/parallel.go
> +// Parallel - running multipule functions in parallel
multiple

2020-10-07 08:35 UTC, yodarshafrir1 commented on pkg/util/parallel.go
> +// Parallel - running multipule functions in parallel
this method isnt used - please delete this file

2020-10-07 09:38 UTC, moshe-kabala commented on cmd/services/node.go
> +func (d *NodeDescriber) GetAllNodeInfos() ([]t.NodeInfo, error, error) {
Fixed

2020-10-07 09:45 UTC, moshe-kabala commented on cmd/services/node.go
> +	}
I didn't use else to cover the case of the internal if code return err too

2020-10-07 09:47 UTC, moshe-kabala commented on cmd/services/node.go
> +		warn = fmt.Errorf("Missing some data. \nresone: Can't access to the prometheus server, \ncause err: %s", err)
fix the typo but the 'n' belong to \n (newline).

2020-10-07 09:47 UTC, moshe-kabala commented on cmd/services/node.go
> +	t "github.com/run-ai/runai-cli/cmd/types"
fixed

2020-10-07 10:00 UTC, moshe-kabala commented on cmd/services/node.go
> +	for _, pod := range d.allPods {
Good Question. this is an old code I don't touch the logic here
may be the right place to filter these pods is here.
what do you think?

2020-10-07 10:07 UTC, moshe-kabala commented on cmd/services/node.go
> +		nodeInfo := t.NewNodeInfo(
I have been debating a lot with myself what to put in there maybe you have some rule of thumb
I put the constructor there because of private fields (I change them to public latter)
I fell that the type and its constructor should be in the same package. and maybe this type need to be in services ?

2020-10-07 11:25 UTC, moshe-kabala commented on cmd/tensorboard.go
> +func isNodeReady(node v1.Node) bool {
Fixed

2020-10-07 11:26 UTC, moshe-kabala commented on cmd/tensorboard.go
> +func getNodeInternalAddress(node v1.Node) string {
Fixed

2020-10-07 11:30 UTC, moshe-kabala commented on cmd/tensorboard.go
> +				address = addr.Address
yes, changed (this is an old code I don't notice to the implement)

2020-10-07 11:30 UTC, moshe-kabala commented on cmd/tensorboard.go
> +	return address
changed

2020-10-07 11:32 UTC, moshe-kabala commented on cmd/types/node.go
> +func (cnv *ClusterNodesView) Render(w io.Writer) {
Why ?
where you think I need to put it?

2020-10-07 11:40 UTC, moshe-kabala commented on cmd/types/pod.go
> +func GetPodResourceStatus(pod v1.Pod) PodResourcesStatus {
yes, it can belong to a converters package. but I don't have so many converters to create a separate package 
I wanted to put it in util but it created circle dependency so I put it there for now. 
do you think a new converters package is a good idea?

2020-10-07 11:50 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	return
changed (remained the if > else instead if  > if)

2020-10-07 11:51 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		return nil, fmt.Errorf("Not found a server for prometheus")
fixed

2020-10-07 11:52 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		err = fmt.Errorf("failed to unmarshall heapster response: %v", err)
fixed

2020-10-07 11:54 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	return
this return the predefined return values in the signature of the function

2020-10-07 12:00 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	// funcs := []func() error{}
I make it in comment because of a bug in the parallel requests to Prometheus. I wish to fix this bug somewhere  ( maybe when we will decide to improve the performance of any command that will use multiple queries vs Prometheus) and then return the comment code - for now, I can leave there a comment. it is OK?

2020-10-07 12:02 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +			// fmt.Print(queryName,"\n\n",rst, "\n\n")
done

2020-10-07 12:02 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		// funcs = append(funcs, getFunc)
done

2020-10-07 12:04 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		// funcs = append(funcs, getFunc)
the same as above commit

2020-10-07 12:05 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	rst := ItemsMap{}
Do you have any idea?

2020-10-07 12:06 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	rst := ItemsMap{}
how about GroupMultipuleQueriesToItemsMap ?

2020-10-07 12:06 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	// err = util.Parallel(funcs...)
the same as above commit

2020-10-07 12:10 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		getFunc();
I want to use goroutine by the parallel function but as I wrote I have a weird bug there (the response overwrite by anther response) maybe you can help me with that

2020-10-07 12:54 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	var mux sync.Mutex
removed

2020-10-07 13:01 UTC, moshe-kabala commented on pkg/ui/table.go
> +func getNesstedVal(t reflect.Value, path []string) (val *reflect.Value) {
because copy past from getNesstedType :) fixed

2020-10-07 13:05 UTC, moshe-kabala commented on pkg/ui/table.go
> +		// todo
just I know :). removed

2020-10-07 13:07 UTC, moshe-kabala commented on pkg/ui/table.go
> +func UnwrapTypePtr(ft reflect.Type) reflect.Type {
field type 
change to t (type)

2020-10-07 13:07 UTC, moshe-kabala commented on pkg/ui/table.go
> +func UnwrapValuePtr(ft reflect.Value) *reflect.Value {
field type
change to v (value)

2020-10-07 13:10 UTC, moshe-kabala commented on pkg/ui/table.go
> +	return items, nil
I forgat to cover the case that the value is not iterable, added

2020-10-07 13:35 UTC, moshe-kabala commented on pkg/ui/table.go
> +//// helpers
some of the helpers belong only to the table some are not. 
I created a file for the general helpers
for table-specific helpers I can create another file table_helpers or remain them in the table. what do you think?

2020-10-07 13:35 UTC, moshe-kabala commented on pkg/ui/table.go
> +	// if need to hide the filed
fixed

2020-10-07 13:42 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +			if !created {
Yes, there are multi-queries and each one contains multi-metrics. the item created dynamically by iterating  over the metrics so the first time that the item id appear in a metric we need to create the item instance

2020-10-07 13:49 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +				return nil, fmt.Errorf("[Prometheos] Not found an 'itemID' (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
first, the error not will happen even though the Prometheus is not available (just if we have a problem with the metrics)
the error will be wrapped in a nice message that Prometheus service not found 
I assume that if this error happens we want the message to understand what went wrong
do you agree?

2020-10-07 13:51 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		// todo: check the metric type
yes for now we query only vector but in the latter, we will query also matrix
I can return an error if the type is not a vector for now

2020-10-07 21:52 UTC, moshe-kabala commented on pkg/ui/table_tes.go
> +func RunTableExampleTes() {
Done

2020-10-07 22:13 UTC, moshe-kabala commented on pkg/util/cache.go
> +	c.mux.Lock()
In the beginning, the cache design to be able to save async data in lazy mode (request the data only if someone ask it) and provide it to any goroutine thread 
for example, we have the following function 
```
func GetSomeData(id string) Data {
   client := clientCache.Get()
   return client.getDataById(id)
}
```

and in another area, we call it in parallel
```
go GetSomeData(id1)
go GetSomeData(id2)
go GetSomeData(id3)
```

the cache will keep that the function "clientCache.Get()" will be call to the data only once
so this is the reason for mutex in the cache when I change any of the cache data
but for now, I don't use it so I can remove it and keep it aside or remained it there

2020-10-07 22:14 UTC, moshe-kabala commented on pkg/util/cache.go
> +	c.mux.Lock()
see comment above

2020-10-08 05:32 UTC, moshe-kabala commented on pkg/util/cache.go
> +	mux sync.Mutex
done

2020-10-08 15:43 UTC, moshe-kabala commented on cmd/services/node.go
> +	for _, pod := range d.allPods {
For now, I filter out all the jobs that are not in running mode, and if the node is not ready I return empty array

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/services/node.go
> +func (d *NodeDescriber) GetAllNodeInfos() ([]types.NodeInfo, error, string) {
The convention in go is to put the `error` last

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/services/node.go
> +	promClient, err := prom.BuildPromethuseClient(d.client)
promethuse - > prometheus

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/services/node.go
> +	var warn string
rename to `warning`

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/services/node.go
> +		if pod.Spec.NodeName == node.Name && pod.Status.Phase == v1.PodRunning{
Running and Pending.
Pending pods can be allocated to nodes as well, they can every get stuck on Pending state and still request the Node's resources

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/util/node.go
> +		//address = nodeInfo.node.Status.Addresses[0].Address
Please delete the comment

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/util/node.go
> +	return "unknown"
https://github.com/run-ai/runai-cli/pull/22#discussion_r500796301

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/types/node.go
> +func (cnv *ClusterNodesView) Render(w io.Writer) {
The package name is `types`, method with the name `Render` doesn't belong here.
You can create a new file under utils

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/types/node.go
> +func (cnv *ClusterNodesView) AddNode(status NodeStatus, gpu NodeGPUResource) {
Same comment as above

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/types/helpers.go
> +func setIntPromData(num *int64, m map[string][]prom.MetricValue, key string) error {
all these method shouldn't be under types

2020-10-11 11:52 UTC, yodarshafrir1 commented on cmd/types/pod.go
> +func GetPodResourceStatus(pod v1.Pod) PodResourcesStatus {
It's ok to create a new package even if it will only 1 converter.
Looks like it belongs utils the most.
the reason you have circle dependency is because you put `func (ni *NodeInfo) GetResourcesStatus() NodeResourcesStatus` under types as well, move them both from this package and it will be fine

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	rst := ItemsMap{}
could work, also `queriesToResponse` would also work.
please also rename the `rst`

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	var mux sync.Mutex
wasn't removed.
You don't need mutex here

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	for queryName, qr := range queryResults {
You should wait for the result

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +			mux.Lock()
No need for mutex.
every query writes to a different key

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	err := util.Parallel(funcs...)
Please don't use this generic method for goroutines, just make the call here

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +		// todo: check the metric type
So write a more detailed todo please

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +			// search the itemId in metric labels
please remove the comment, it's obvious

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +				return nil, fmt.Errorf("[Prometheos] Not found an 'itemID' (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
The problem is with the word `itemID`.
You can write 
```suggestion
				return nil, fmt.Errorf("[Prometheos] Failed to find key: (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
```

2020-10-11 11:52 UTC, yodarshafrir1 commented on pkg/util/cache.go
> +	c.mux.Lock()
If you don't use the mutex please delete it

2020-10-11 14:00 UTC, moshe-kabala commented on cmd/services/node.go
> +func (d *NodeDescriber) GetAllNodeInfos() ([]types.NodeInfo, error, string) {
done

2020-10-11 14:39 UTC, moshe-kabala commented on cmd/services/node.go
> +	promClient, err := prom.BuildPromethuseClient(d.client)
done

2020-10-11 14:40 UTC, moshe-kabala commented on cmd/services/node.go
> +	var warn string
done

2020-10-11 14:41 UTC, moshe-kabala commented on cmd/services/node.go
> +		if pod.Spec.NodeName == node.Name && pod.Status.Phase == v1.PodRunning{
good to know, 
done

2020-10-11 14:42 UTC, yodarshafrir1 requested changes
Let's talk about this refactor

2020-10-11 15:11 UTC, moshe-kabala commented on cmd/util/node.go
> +		//address = nodeInfo.node.Status.Addresses[0].Address
done

2020-10-11 15:17 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	err := util.Parallel(funcs...)
The advantage of this util method is it makes the logic of waiting for you

2020-10-11 15:18 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +			// search the itemId in metric labels
done

2020-10-11 15:28 UTC, moshe-kabala commented on cmd/get/get.go
> +func SearchTrainingJob(kubeClient *client.Client, jobName string, trainingType string, namespaceInfo cmdTypes.NamespaceInfo) (job trainer.TrainingJob, err error) {
It used by exec and logs packages. it better to put it in the util but I don't do that refactor yet

2020-10-11 15:29 UTC, moshe-kabala commented on cmd/job/delete/delete.go
> +		trainingTypes, err = get.GetTrainingTypes(jobName, namespaceInfo.Namespace, kubeClient.GetClientset())
yes agree. but I must to that to separate them first the seconde step is to move that logic into share util package

2020-10-11 15:32 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	for queryName, qr := range queryResults {
the parallel function do it for me

2020-10-11 16:34 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +			mux.Lock()
removed

2020-10-12 09:21 UTC, moshe-kabala commented on cmd/types/node.go
> +func (cnv *ClusterNodesView) AddNode(status NodeStatus, gpu NodeGPUResource) {
All the function in types passed to a helpers package

2020-10-12 09:21 UTC, moshe-kabala commented on cmd/types/helpers.go
> +func setIntPromData(num *int64, m map[string][]prom.MetricValue, key string) error {
All the function in types passed to a helpers package

2020-10-12 09:22 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	for queryName, qr := range queryResults {
The code change as we talked

2020-10-12 10:10 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	err := util.Parallel(funcs...)
I removed the parallel function

2020-10-12 12:01 UTC, moshe-kabala commented
moved to https://github.com/run-ai/runai-cli/pull/30

2020-10-12 12:01 UTC, closed without merging