fix missing gcloud dependancy in 'push' job
run-ai/runai-cli pull request #223
Opened 2022-02-21 17:37 UTC by romanbaron

2022-02-21 17:40 UTC, itayvallach submitted a review, later dismissed

2022-02-22 07:47 UTC, keinanDaniel approved these changes

2022-02-22 07:49 UTC, keinanDaniel commented on .circleci/config.yml
>    push:
need in release as well

2022-02-22 07:50 UTC, keinanDaniel requested changes

2022-02-22 07:50 UTC, keinanDaniel commented on .circleci/config.yml
> +    executor: gcp-cli/default
need in release as well

2022-02-22 08:32 UTC, romanbaron commented on .circleci/config.yml
> +    executor: gcp-cli/default
done :)

2022-02-22 08:35 UTC, keinanDaniel submitted a review, later dismissed

2022-02-22 11:49 UTC, keinanDaniel approved these changes

2022-02-22 12:37 UTC, omer-dayan approved these changes

2022-02-22 12:38 UTC, merged