Add suffix to the job name if it already exists
run-ai/runai-cli pull request #28
Opened 2020-10-07 22:47 UTC by omer-dayan

2020-10-08 07:37 UTC, yodarshafrir1 requested changes

2020-10-08 07:37 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +	submitArgs.Name = mutatedName
Why not change the name inside the method `SubmitJob`?

2020-10-08 07:37 UTC, yodarshafrir1 commented on cmd/job/submit/submit_runai.go
> +	submitArgs.Labels[kubectl.BaseNameLabel] = submitArgs.Name
Why only for runaijobs? let's do it for all jobs.
Let's move it to the `SubmitJob` method

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +func SubmitJob(name string, trainingType string, namespace string, values interface{}, environmentValues string, chart string, clientset kubernetes.Interface, dryRun bool) (string, error) {
Let's move the submitargs to this method and change the name of the workload here

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	args := []string{"get", "runaijob.run.ai"}
Let's support all workloads type?

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	args = append(args, "--selector=" + BaseNameLabel + "=" + baseName)
Great job using selectors here!!

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	if types.KubeConfig != "" {
Why is this needed?

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	cmd := exec.Command(binary, args...)
Why did you decide to use `kubectl` command and not API server calls? 
here is an example:
https://github.com/run-ai/runai-cli/blob/master/cmd/trainer/trainer_runai.go#L44

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		generatedJobFiles, err := generateJobFiles(name, namespace, values, environmentValues, chart)
there's some duplication code here with normal job creation, can we extract to methods?

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	return "", "", nil, fmt.Errorf("The job %s already exists, please delete it first. use '%s delete %s'", name, config.CLIName, name)
I'd rephrase the error here.
we claim to have this feature, maybe more in the directions of: failed to create job please submit again.

2020-10-08 07:37 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +				jobName, name, jobFiles, err = forceGenerateJobFiles(name, jobName, namespace, environmentValues, chart, values)
Not a must: This area is a bit confusing, don't be afraid to make some small refactor here

2020-10-08 09:15 UTC, omer-dayan commented on pkg/util/kubectl/kubectl.go
> +	if types.KubeConfig != "" {
Removed, really not needed

2020-10-08 09:15 UTC, omer-dayan commented on cmd/job/submit/submit_mpi.go
> +	submitArgs.Name = mutatedName
Done

2020-10-08 09:15 UTC, omer-dayan commented on cmd/job/submit/submit_runai.go
> +	submitArgs.Labels[kubectl.BaseNameLabel] = submitArgs.Name
Done

2020-10-08 09:15 UTC, omer-dayan commented on pkg/util/kubectl/kubectl.go
> +	cmd := exec.Command(binary, args...)
Couldnt find a way to get the data, because we are using CDRs

2020-10-08 09:15 UTC, omer-dayan commented on pkg/util/kubectl/kubectl.go
> +	args := []string{"get", "runaijob.run.ai"}
Arent they all of them under runaijob.run.ai?

2020-10-08 10:01 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	args := []string{"get", "runaijob.run.ai"}
No, we have mpi jobs, statefulsets and runaijobs

2020-10-08 10:01 UTC, yodarshafrir1 commented on pkg/util/kubectl/kubectl.go
> +	cmd := exec.Command(binary, args...)
let's have a zoom session and i will show how can we handle this

2020-10-08 14:23 UTC, yodarshafrir1 requested changes
Looking good, please see my notes

2020-10-08 14:23 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +func forceGenerateJobFiles(name *string , namespace, environmentValues, chart string, values interface{}, countFunc getJobCount) (*JobFiles, error) {
Can we pass submitArgs.Labels instead of this interface and assign the labels?

2020-10-08 14:23 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +type getJobCount func(name, namespace string) (int, error)
Can you put this on the top of the file please
Please also add it suffix for `Fn`

2020-10-08 14:23 UTC, yodarshafrir1 commented on cmd/job/submit/submit_runai.go
> +		return len(list.Items), nil
what happens on the following scenario:
submit job
submit job
submit job

delete job
submit job

will it work?

2020-10-08 14:23 UTC, yodarshafrir1 commented on cmd/job/submit/submit_runai.go
> +		list, err := runaiclientset.RunV1().RunaiJobs(namespace).List(metav1.ListOptions{LabelSelector: fmt.Sprintf("%s=%s", workflow.BaseNameLabel, name)})
please support interactive jobs as well
you can submit them by adding `--interactive` flag

2020-10-08 14:23 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	return nil, fmt.Errorf("Could not submit %s. Pleas try again", name)
`Pleas` -> `Please`

2020-10-08 14:23 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +		list, err := client.GetClientset().CoreV1().Pods(namespace).List(metav1.ListOptions{LabelSelector: fmt.Sprintf("%s=%s", workflow.BaseNameLabel, name)})
why pods? get MPIJobs no?

2020-10-08 14:23 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +	countJobFunc := func(name, namespace string) (int, error) {
Please move the comment you have here to the relevant place

2020-10-11 08:28 UTC, yodarshafrir1 commented on cmd/job/submit/submit_runai.go
> +		return len(list.Items), nil
@omer-dayan

2020-10-11 08:44 UTC, yodarshafrir1 requested changes
Looking good, almost done

2020-10-11 08:44 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		jobSuffix := strconv.Itoa(count + i - 1)
Not sure i understand why the -1

2020-10-11 08:44 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +func forceGenerateJobFiles(name *string , namespace, environmentValues, chart string, values interface{}, countFunc getJobCountFunc) (*JobFiles, error) {
force can miss lead here.
let's rename to `generateJobFilesWithNewName` or something similar

2020-10-11 08:44 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	for i := 0; i < forceSubmitRetries; i++ {
rename this as well please

2020-10-11 08:44 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		jobSuffix := strconv.Itoa(count + i - 1)
https://github.com/run-ai/runai-cli/pull/28#discussion_r501758946 I still think this will not work well

2020-10-12 10:18 UTC, yodarshafrir1 requested changes

2020-10-12 10:18 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +		return jobCount, nil
shouldn't we return `jobCount+1`?

2020-10-12 10:23 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +	flags.AddBoolNullableFlag(command.Flags(), &(submitArgs.generateName), "generate-name", "", "Allow the CLI to change the name of the job if the job name already exists")
Maybe this is more suitable: 
`Add suffix to the job name if a job with the submitted name already exists`
@yarongol What do you think?

2020-10-12 10:36 UTC, yarongol commented on cmd/job/submit/submit_mpi.go
> +	flags.AddBoolNullableFlag(command.Flags(), &(submitArgs.generateName), "generate-name", "", "Allow the CLI to change the name of the job if the job name already exists")
I don't have any context @yodarshafrir1  on what this pull request is about.
Why do we want to add a suffix to the job if it already exists? It can lead to confusion where you don't read the output and think that the job you created is the original job.
Why not just return an error "Job already exists, please use a different name or delete the original job"

2020-10-23 14:38 UTC, closed without merging