RUN-967 - Improving the top node command
run-ai/runai-cli pull request #32
Opened 2020-10-12 16:22 UTC by moshe-kabala

2020-10-13 12:18 UTC, yodarshafrir1 requested changes
Great Job so far,
This PR looks much more organized, the files are more organized, the functions as well.

Please try to name your variables better than single letters, `itemMap`, `generalField` these names are very confusing.

Also, please see that the fractional GPUs are handled well and we don't have a mix here - the fractional GPU handling also looks very confusing.

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	if cnv.GPUs > 0 {
what about fractions?

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +		gpuUsage = float64(cnv.AllocatedGPUs) / float64(cnv.GPUs) * 100
what about fractions

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	cnv.AllocatedFractionGPUs += float64(gpu.AllocatedFraction)
why can't we add fractions to the `AllocatedGPUs` field

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	if cnv.GPUs != cnv.GPUsOnReadyNode {
Do we count fractional allocated GPUs here?

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	if float64(cnv.AllocatedGPUs) != cnv.AllocatedFractionGPUs {
Do we have 2 logs, 1 for fractions 1 for full?

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	MetricStatus string
Remove comment and rename to `MetricStatusResult`

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	// MetricType the possible metice type
typo

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	MetricType string
Please remove comment and name better

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	MultiQueries = map[string]string
rename to `MultiQueries` to `queryNameToQuery` and remove comment

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	ItemsMap = map[string]map[string][]MetricValue
Why name a variable with this generic name, please rename

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +		go (func(query, name string) {
Great job here!

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	for i := 0; i< len(q); i++ {
Let's wait for the channels.
please use waitgroups
Please use https://gobyexample.com/waitgroups here

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +	for queryName, qr := range queryResults {
`qr` -> `queryResult`
You are adding hard logic with all the goroutines and the wait - this is not a simple thing, let's help other understand with better naming

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +		// todo: now we are handling only result type = "vector", consider handling more result type in the fuehrer
you meant `future`?

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/prometheus/prometheus.go
> +				return nil, fmt.Errorf("[Prometheos] Failed to find key: (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
Prometheos -> Prometheus

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/services/node/node.go
> +	// get prometheus node resources data
Please remove this comment, it's obvious

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/services/node/node_info.go
> +	p, ok := ni.PrometheusNode[ni.Node.Name]
Please rename that `p`, what does it mean

2020-10-13 12:18 UTC, yodarshafrir1 commented on pkg/services/node/node_info.go
> +		ok = (int(value.Value()) > 0)
I don't this this `int` is needed

2020-10-13 12:57 UTC, moshe-kabala commented on cmd/top/top_node.go
> +	generalFiled = []string{
changed to generalNodeInfoFields

2020-10-13 12:59 UTC, moshe-kabala commented on cmd/top/top_node.go
> +			nodeInfos, warn, err := nd.GetAllNodeInfos()
fixed

2020-10-13 13:00 UTC, moshe-kabala commented on cmd/top/top_node.go
> +	defultHidden = []string{
changed to defaultHiddenFields

2020-10-13 13:02 UTC, moshe-kabala commented on cmd/top/top_node.go
> +	// Print Cpu and memory table
deleted

2020-10-13 13:05 UTC, moshe-kabala commented on cmd/top/top_node.go
> +		info := nodeInfo.GetGeneralInfo()
change to generalNodeInfo 
( `nodeInfo` is already declared in this scope)

2020-10-13 13:07 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +	if float64(cnv.AllocatedGPUs) != cnv.AllocatedFractionGPUs {
yes if the fraction and units are not the same

2020-10-13 13:08 UTC, moshe-kabala commented on pkg/services/node/node_info.go
> +		ok = (int(value.Value()) > 0)
fixed

2020-10-13 13:32 UTC, moshe-kabala commented on pkg/services/node/node_info.go
> +	p, ok := ni.PrometheusNode[ni.Node.Name]
changed to promDataByNode

2020-10-13 13:33 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +				return nil, fmt.Errorf("[Prometheos] Failed to find key: (%s) on the metric query: %s => %s",itemID, queryName, q[queryName] )
fixed

2020-10-13 13:35 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +		// todo: now we are handling only result type = "vector", consider handling more result type in the fuehrer
yes, fixed

2020-10-13 13:37 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	for queryName, qr := range queryResults {
absolutely, fixed

2020-10-13 13:42 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	MultiQueries = map[string]string
change to `QueryNameToQuery`

2020-10-13 14:05 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	// MetricType the possible metice type
fixed

2020-10-13 14:13 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +	cnv.AllocatedFractionGPUs += float64(gpu.AllocatedFraction)
currently, we calculate the allocated GPU as a fraction and as a units
1. how many units are allocated
2. the amount of all GPU allocated (fraction and wheel units)
I changed the `AllocatedGPUs` to `AllocatedGpuUnits` to be more clear with that

2020-10-13 14:15 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +	if cnv.GPUs != cnv.GPUsOnReadyNode {
the wheel function is just print(render) the clusterNodesData and not calculate it

2020-10-13 14:16 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +		gpuUsage = float64(cnv.AllocatedGPUs) / float64(cnv.GPUs) * 100
I print it in row 49

2020-10-13 14:16 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +	if cnv.GPUs > 0 {
I print it in row 49

2020-10-13 14:21 UTC, moshe-kabala commented on pkg/helpers/resource_helpers.go
> +	rl.GPUs += kubeQuantityToFloat64(krl, util.NVIDIAGPUResourceName) + kubeQuantityToFloat64(krl, util.DeprecatedNVIDIAGPUResourceName)
This is a general resource list  usage and not specific for allocated (it can be requested, limits or usage) so our allocated fraction get attention when we convert the node info into nodeResourceStatus

2020-10-13 15:25 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	ItemsMap = map[string]map[string][]MetricValue
change to `MetricResultsAsItems`

2020-10-13 15:33 UTC, moshe-kabala commented on pkg/prometheus/prometheus.go
> +	for i := 0; i< len(q); i++ {
WaitGroup is a nice feature but in our case, we are already using channels to pass the data and therefore we did not need it.
https://gobyexample.com/channel-synchronization

2020-10-14 08:11 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	cnv.AllocatedFractionGPUs += float64(gpu.AllocatedFraction)
This means that `AllocatedGPUs` is a bad name and can mislead in the future, rename it to `AllocatedWholeGPUs`

2020-10-14 08:48 UTC, yodarshafrir1 approved these changes
2 last notes (not a must)
Great job here!

2020-10-14 08:48 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +	cnv.AllocatedGpuFractions += float64(gpu.AllocatedFraction)
no need to cast to float

2020-10-14 08:48 UTC, yodarshafrir1 commented on pkg/helpers/node_helpers.go
> +		gpuUsage = float64(cnv.AllocatedGpuUnits) / float64(cnv.GPUs) * 100
no need to cast to float

2020-10-14 09:22 UTC, merged