Submit job ConfigMap with isInteractive flag
run-ai/runai-cli pull request #34
Opened 2020-10-13 13:38 UTC by omer-dayan

2020-10-13 15:06 UTC, yodarshafrir1 requested changes

2020-10-14 11:14 UTC, yodarshafrir1 requested changes
Looking good, few small comments

2020-10-14 11:14 UTC, yodarshafrir1 commented on cmd/job/delete/delete.go
> +		maybeConfigMapName := fmt.Sprintf("%s-%s", name, trainingType)
what do you think about `configMapPrefix`

2020-10-14 11:14 UTC, yodarshafrir1 commented on cmd/job/delete/delete.go
> +func deleteTrainingJob(kubeClient *client.Client, jobName string, namespaceInfo types.NamespaceInfo, trainingType string) error {
trainingType is unused

2020-10-14 11:14 UTC, yodarshafrir1 commented on cmd/job/delete/delete.go
> +	if len(optionalConfigMaps) == 0 {
We will remove that part on the next stages right?

2020-10-14 11:14 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	jobName := configMapName
No reason to use `jobName` here, the name is just misleading

2020-10-14 11:14 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +func GetJobName(name string, trainingType string, isInteractive bool) string {
GetConfigMapName no?

2020-10-14 11:14 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		jobName := GetJobName(name, trainingType, isInteractive)
configMapName

2020-10-14 11:14 UTC, yodarshafrir1 commented on cmd/job/delete/delete.go
> +func deleteTrainingJob(kubeClient *client.Client, jobName string, namespaceInfo types.NamespaceInfo, trainingType string) error {
This method already looks much better than before, good job 🥇

2020-10-14 11:32 UTC, omer-dayan commented on cmd/job/delete/delete.go
> +	if len(optionalConfigMaps) == 0 {
Yes. we will not talk in terms of config map at all

2020-10-14 11:41 UTC, yodarshafrir1 requested changes

2020-10-14 11:41 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		jobName := GetConfigMapName(name, trainingType, isInteractive)
Please rename to `configMapName`

2020-10-14 11:53 UTC, yodarshafrir1 approved these changes
![Alt Text](https://media.giphy.com/media/d2Z9QYzA2aidiWn6/giphy.gif)

2020-10-14 11:54 UTC, merged