RUN-1087 - Show top node details on a specific node
run-ai/runai-cli pull request #38
Opened 2020-10-14 17:29 UTC by moshe-kabala

2020-10-18 10:07 UTC, yodarshafrir1 requested changes
Need to decide whether the `top node` command should have 2 commands or just 1.

2020-10-18 10:07 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs_test.go
> +		expactedPath := "test_expected/key_value_pairs_test_1.txt"
`expactedPath` -> expectedPath

2020-10-18 10:07 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs_test.go
> +func record_at_file(fileName string, content string) {
This method is unused

2020-10-18 10:07 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs.go
> +		perant   *PairMeta
parent

2020-10-18 10:07 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs.go
> +	// if need to hide the field
This comment belongs here?

2020-10-18 10:10 UTC, moshe-kabala commented on cmd/top/top_node_name.go
> +			matchNodeInfo = &nodeInfos[i]
fixed

2020-10-18 10:10 UTC, moshe-kabala commented on cmd/top/top_node_name.go
> +		GPUs:   nodeResourcesConvertor.ToGpus(),
Yes good idea

2020-10-18 10:16 UTC, moshe-kabala commented on cmd/top/top_node.go
> +		Use:   "node [NODE_NAME]",
The different between 
> top node
> top node node_name
is just a node_name argument, and I don't fine a way to split them into a tow commands in cobra. so as we talk my suggestion to solve this is to change the top node => top nodes. but maybe let's wait for Yaron for that?

2020-10-18 10:21 UTC, moshe-kabala commented on pkg/helpers/node_helpers.go
> +func AddNodeToClusterNodes(cnv *types.ClusterNodesView, status types.NodeStatus, gpu *types.NodeGPUResource) {
Fixed

2020-10-18 10:28 UTC, moshe-kabala commented on pkg/helpers/node_resources_status_helpers.go
> +	if result.Capacity == 0 {
avoiding to display all the GPUs fields on a node that don't has GPUs 
so instead
```
GPUs
    Capacity               0
    Allocated Units.   0
    ...
    Usage                   0%
```
I will just display
```
GPUs          <none>
```

2020-10-18 11:02 UTC, moshe-kabala commented on pkg/helpers/node_resources_status_helpers.go
> +	if result.Capacity == 0 {
the same as above commend, any resource that not exist will not show all its fields

2020-10-18 11:04 UTC, moshe-kabala commented on pkg/services/node/node.go
> +		err = nil // change the error to be just a warning
I need to reset the err variable to be nil (otherwise the function returns both err and warning)

2020-10-18 11:05 UTC, moshe-kabala commented on pkg/ui/field_meta.go
> +			return FieldMeta{}, fmt.Errorf("[UI::FieldMeta] Not found format function for format name: %s  on field name: %s . Please make sure to include it in the TableOpt.CustomFormat", format, key)
no, it is for the developer/testing to understand what wrong

2020-10-18 11:07 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +		// if there is at least one filed on the root of the struct
fixed

2020-10-18 11:11 UTC, moshe-kabala commented on pkg/ui/key_value_pairs_test.go
> +		expactedPath := "test_expected/key_value_pairs_test_1.txt"
fixed

2020-10-18 11:12 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +		perant   *PairMeta
fixed

2020-10-18 11:22 UTC, moshe-kabala commented on pkg/ui/key_value_pairs_test.go
> +func record_at_file(fileName string, content string) {
This is a helper method to record the test result to a file - I use it just when I test the output of the UI

2020-10-18 11:23 UTC, moshe-kabala commented on pkg/ui/table_test.go
> +		// for test debugging
It help me to record the result into a file (whenever I change something in the output of the table I need to use this line of code)

2020-10-18 11:24 UTC, moshe-kabala commented on pkg/ui/key_value_pairs_test.go
> +		// for test debugging
It help me to record the result into a file (whenever I change something in the output of the key_value_pairs I need to use this line of code)

2020-10-18 11:25 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +	// if need to hide the field
removed

2020-10-18 12:24 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +			if !strings.Contains(path, ".") {
Because every struct can contain many fields and the definition of which fields to show and which to hide will be verbose, especially when you have a nested struct. I create a mechanism to make this definition easier for most use cases 

In general, the decision of which fields to hide or show is based on three parameters
hide - a list of path
show - a list of path
showByDefult - boolean

in case of collision between hide and show list the show is take

each field will be defined dynamically showByDefult for itself and it will be fixed by one of these - (The latter determines)
1. its parent showByDefult
2. the user set the filed in the hide list - will be false
3. the user set the filed in the show list - will be true

if showByDefult is false the field not will show and its children will be set as showByDefult = false unless they are in the hide or show list as mention above

the problem is that the root fields don't have a parent and I need to decide its showByDefult.
so it solved by allowed a user to set it. in case that a user did not set it - it will be calculated by the show list, so if there is at least one field on the root in the show list it will be set to false otherwise is true

I know the mechanism it a bit complicated but It did the work very well I can add examples of the cases that I solved with this mechanism if you will

2020-10-18 12:26 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +	absolutePathStr := strings.Join(absolutePath, ".")
the structure here is a tree, I first calculate the absolute Path and then check if show/hide the field

2020-10-18 12:26 UTC, moshe-kabala commented on cmd/top/top_node_name.go
> +			matchNodeInfo = &nodeInfos[i]
fixed

2020-10-18 12:38 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +			if !strings.Contains(path, ".") {
I refactor the code and capsulate it into A DisplayOpt struct and put there an explanation

2020-10-21 12:49 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs.go
> +		perant   *PairMeta
Please rename `perant` to `parent` all over the file

2020-10-21 13:47 UTC, yodarshafrir1 requested changes
Looks great.
Please see my notes.

2020-10-21 13:47 UTC, yodarshafrir1 commented on pkg/services/node/node.go
> +		err = nil // change the error to be just a warning
I understand.
Can we just rename the `err` variable here so it will not be the returned value:
`promData, queryErr = promClient.GroupMultiQueriesToItems(nodePQs, promethesNodeLabelID)`

2020-10-21 13:47 UTC, yodarshafrir1 commented on pkg/ui/display.go
> +func (opt *DisplayOpt) calcFiledShowByDefult(path []string ,parentShowByDefault bool) bool{
filed-> field
defult-> default

2020-10-21 13:47 UTC, yodarshafrir1 commented on cmd/node/describe_node.go
> +		Use:   "node [...NODE_NAME]",
On the usage we want to show 2 options, like kubectl:

```
# Describe a node
  runai describe node [NODE_NAME]

# Describe all nodes
  runai describe node
```

2020-10-21 13:47 UTC, yodarshafrir1 commented on cmd/node/describe_node.go
> +				handleDescriveSpecificNodes(nodeInfos, args...)
`handleDescriveSpecificNodes` -> `handleDescribeSpecificNodes`

2020-10-21 13:47 UTC, yodarshafrir1 commented on cmd/node/describe_node.go
> +		Args:  cobra.RangeArgs(0, 1),
do we support multiple nodes?

2020-10-21 13:47 UTC, yodarshafrir1 commented on pkg/ui/key_value_pairs.go
> +func (td *keyValuePairsData) Render(w io.Writer, row interface{}) KeyValuePairs {
why td?

2020-10-21 13:49 UTC, yodarshafrir1 commented on cmd/node/describe_node.go
> +		Args:  cobra.RangeArgs(0, 1),
Let's support few args and show data about all the args

2020-10-21 14:25 UTC, moshe-kabala commented on cmd/resource/describe.go
> +		Short: "Display detailed information about Runai resources.",
deleted

2020-10-21 14:25 UTC, moshe-kabala commented on cmd/resource/top.go
> +		Short: "Display top information about Runai resources.",
deleted

2020-10-21 14:26 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +func (td *keyValuePairsData) Render(w io.Writer, row interface{}) KeyValuePairs {
yes CP, fixed

2020-10-21 14:28 UTC, moshe-kabala commented on cmd/node/describe_node.go
> +		Args:  cobra.RangeArgs(0, 1),
yes we support, (deleted the range limitation)

2020-10-21 14:30 UTC, moshe-kabala commented on pkg/ui/display.go
> +func (opt *DisplayOpt) calcFiledShowByDefult(path []string ,parentShowByDefault bool) bool{
fixed

2020-10-21 14:34 UTC, moshe-kabala commented on cmd/node/describe_node.go
> +		Use:   "node [...NODE_NAME]",
nice, added to example

2020-10-21 14:38 UTC, moshe-kabala commented on cmd/node/describe_node.go
> +				handleDescriveSpecificNodes(nodeInfos, args...)
fixed

2020-10-21 14:42 UTC, moshe-kabala commented on pkg/ui/key_value_pairs.go
> +func (td *keyValuePairsData) Render(w io.Writer, row interface{}) KeyValuePairs {
change to kvd  (key value data)

2020-10-28 16:13 UTC, merged