Submit a job with unique name across all the "job types" namespace and generate suffix
run-ai/runai-cli pull request #39
Opened 2020-10-18 12:27 UTC by omer-dayan

2020-10-19 11:11 UTC, yodarshafrir1 requested changes

2020-10-19 11:11 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	return nil, fmt.Errorf("could not create job, please try again later")
How about?
`Job creation has failed. Please try again`

2020-10-19 11:11 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	if err != nil {
Don't we first want to call the `defer` ?

2020-10-19 11:11 UTC, yodarshafrir1 commented on cmd/job/list/list.go
> +		ui.Line(w, invalidJob, "Invalid job. Please delete it!", "", "", "", "", "", "", "", "", "")
Since you put so much text in the `STATUS` column it can cause an indentation issue

2020-10-19 11:11 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +	flags.AddBoolNullableFlag(flagSet, &submitArgs.GenerateName, "generate-name", "", "Generate suffix to the job if the original name is occupied")
`occupied` -> `used`

2020-10-19 12:17 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +	FamilyNameLabelSelectorName = "FamilyName"
Except of FamilyNameLabelSelectorName

2020-10-19 12:18 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +	FamilyNameLabelSelectorName = "FamilyName"
Lack of better term to describe the connection among all those that has the same base name

2020-10-19 12:20 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +	if err != nil {
If there is an error it means the jobFiles object is not generated. no need to clean it in such case

2020-10-19 12:25 UTC, omer-dayan commented on cmd/job/list/list.go
> +		ui.Line(w, invalidJob, "Invalid job. Please delete it!", "", "", "", "", "", "", "", "", "")
The width of the column derived from the widest cell in that column. This text seems pretty fine compared to other text can be in this column
<img width="389" alt="Screen Shot 2020-10-19 at 15 25 15" src="https://user-images.githubusercontent.com/10087174/96450810-5ab48c00-121f-11eb-95af-b78031530089.png">

2020-10-19 12:26 UTC, omer-dayan commented on cmd/job/list/list.go
> +		ui.Line(w, invalidJob, "Invalid job. Please delete it!", "", "", "", "", "", "", "", "", "")
Its seems natural (In my opinion) next to the ImagePullBackOff

2020-10-19 14:36 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	FamilyNameLabelSelectorName = "FamilyName"
Isn't just ruins from the part you created different prefix for different family, 1 family was the MPI and 1 was RunaiJob?
Why not just baseNameLabel or baseLabelSelector? we no longer have anything to do with families

2020-10-19 14:45 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	if err != nil {
If `generateJobFiles` returns an error at the last part of the method, on `kubectl.SaveAppInfo(template, namespace)` we will have files, don't we?

2020-10-19 14:50 UTC, yodarshafrir1 requested changes
Please also see my notes on the previous review

2020-10-19 14:50 UTC, yodarshafrir1 commented on cmd/job/list/list.go
> +					if item.Labels[workflow.FamilyNameLabelSelectorName] != "" {
Not sure why do we need this condition?
Why not always show the row on the job list if configmap exist and job doesn't?
Also every new job will have this label, and we want to present old configmaps as well.
Am I missing something?

2020-10-19 14:50 UTC, yodarshafrir1 commented on cmd/job/list/list.go
> +		ui.Line(w, invalidJob, "Invalid job. Please delete it!", "", "", "", "", "", "", "", "", "")
The `list` command is very wide already, we don't want to make it wider and we don't want to tell the user what actions to do on the status.
You can show the status as: `StaleJob` or `Stale` or `InvalidJob` or `Invalid`
If the user will want to get more information he can run the `get` command and understand that the job should be deleted.

2020-10-19 15:02 UTC, omer-dayan commented on cmd/job/list/list.go
> +		ui.Line(w, invalidJob, "Invalid job. Please delete it!", "", "", "", "", "", "", "", "", "")
I Definitaly agree about that!

2020-10-19 15:16 UTC, yodarshafrir1 requested changes

2020-10-19 15:16 UTC, yodarshafrir1 commented on cmd/get/get.go
> +		configMap, err := kubeClient.GetClientset().CoreV1().ConfigMaps(namespaceInfo.Namespace).Get(name, metav1.GetOptions{})
What about all the other commands (bash, exec, logs)?

2020-10-19 15:19 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +	if err != nil {
Yes, but in case of error the object return nil. And its better to handle this inside the generateJobFiles (Done)

2020-10-19 15:44 UTC, omer-dayan commented on cmd/get/get.go
> +		configMap, err := kubeClient.GetClientset().CoreV1().ConfigMaps(namespaceInfo.Namespace).Get(name, metav1.GetOptions{})
Unfortunately all of the other commands use the function in the GET package. that means all the commands gets to this line of code

2020-10-19 15:46 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +	FamilyNameLabelSelectorName = "FamilyName"
BaseNameLabelSelector is chosen! I didnt like the family work either

2020-10-19 15:49 UTC, omer-dayan commented on cmd/job/list/list.go
> +					if item.Labels[workflow.FamilyNameLabelSelectorName] != "" {
Thats the exact reason I did it. From now on, we dont do config map name like "test-runaijob" or "test-mpijob". if the job called "test" then the configmap is called "test". So old cases need seperate logic (However, I dont think its worth doing - its a feature we add to the CLI, it make sense its not working retroactive)

2020-10-20 13:43 UTC, yodarshafrir1 requested changes
last cycle

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	BaseNameLabelSelectorName  = "FamilyName"
`FamilyName` -> `base-name`?

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	baseIndexLabelSelectorName = "FamilyIndex"
`FamilyIndex` ->`base-name-index` ?

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	if err != nil {
Great

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		return nil, fmt.Errorf("there is another job with the name %s, you can either delete it or you can use the --generate-name flag", maybeConfigMapName)
this is the old message: 
`The job <job-name> already exists, please delete it first. use 'runai delete <job-name>`
so maybe use this string:
`The job %s already exists, either delete it first (use 'runai delete <job-name>' ) or submit the job again using the flag  --generate-name`

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		fmt.Println("Generate the template on:")
do we really want this print?

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +		fmt.Println(jobFiles.template)
do we really want this print?

2020-10-20 13:43 UTC, yodarshafrir1 commented on pkg/workflow/workflow.go
> +	fmt.Println(jobFiles.template)
do we really want this print?

2020-10-20 13:43 UTC, yodarshafrir1 commented on cmd/job/list/list.go
> +							invalidJobs = append(invalidJobs, item.Name)
do we really want this print?

2020-10-20 13:43 UTC, yodarshafrir1 commented on cmd/job/list/list.go
> +						if jobsMap[item.Name] == false {
let's discuss this

2020-10-20 13:49 UTC, yodarshafrir1 requested changes

2020-10-20 13:49 UTC, yodarshafrir1 commented on cmd/job/delete/delete.go
> +				err = workflow.DeleteJob(jobName, namespaceInfo, kubeClient.GetClientset())
Please add backward compatibility for deletion of old jobs

2020-10-21 07:36 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +		fmt.Println("Generate the template on:")
Its a dry-run flag. We use to print it in the past.
You add dry run and get the YAML that is going to be sent to the server

2020-10-21 07:36 UTC, omer-dayan commented on pkg/workflow/workflow.go
> +		fmt.Println(jobFiles.template)
Its a dry-run flag. We use to print it in the past.
You add dry run and get the YAML that is going to be sent to the server

2020-10-21 10:44 UTC, yodarshafrir1 requested changes
Good job!
Let's wait with pushing this for the 2nd PR

2020-10-21 14:24 UTC, yodarshafrir1 approved these changes
🥇

2020-10-21 14:24 UTC, merged