RUN-1129 adding createBy=RunaiJob label in the runai trainer
run-ai/runai-cli pull request #45
Opened 2020-10-22 16:48 UTC by moshe-kabala

2020-10-22 22:25 UTC, yodarshafrir1 requested changes

2020-10-22 22:25 UTC, yodarshafrir1 commented on cmd/trainer/trainer_runai.go
> +	// add created by runai label if it don't existed
You should filter the `get` command by this label.
Why add this label?
What about the bug you needed to fix where the CLI crashed?

2020-10-23 09:31 UTC, moshe-kabala commented on cmd/trainer/trainer_runai.go
> +	// add created by runai label if it don't existed
The get action will be filtered according to these labels
So the problem is solved because I only got the pods created by runai.
I added another check (pod.OwnerReferences! = Zero) but this case should not happen

2020-10-23 09:32 UTC, moshe-kabala commented on cmd/trainer/trainer_runai.go
> +	// add created by runai label if it don't existed
Also, I already test it to see that the problem solved

2020-10-23 09:38 UTC, yodarshafrir1 commented on cmd/trainer/trainer_runai.go
> +	// add created by runai label if it don't existed
We want to show all jobs/pods, not only those who were created by the cli.
This is not the right solution

2020-10-23 09:42 UTC, moshe-kabala commented on cmd/trainer/trainer_runai.go
> +	// add created by runai label if it don't existed
I assume from the code that the TrainRunai get the runai job and latter search for its pods and these pod should to contain the createBy: runai label. 
where I am wrong ?

2020-10-25 11:26 UTC, closed without merging

2020-10-25 11:26 UTC, moshe-kabala commented
just adding the `pod.OwnerReferences != nil`  to master