Ability to make field mandatory
run-ai/runai-cli pull request #53
Opened 2020-10-29 14:09 UTC by omer-dayan

2020-11-01 14:14 UTC, yodarshafrir1 requested changes

2020-11-01 14:14 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		} else {
can we merge this with the next lines?

2020-11-01 14:14 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		} else {
same

2020-11-01 14:14 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		} else {
same

2020-11-01 14:14 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +	if value == nil && required {
Can you create a method to check if value is nil and required and panics?

2020-11-01 14:28 UTC, yodarshafrir1 requested changes

2020-11-01 14:28 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		if err != nil && templateField.Value != "" {
if error print that we failed to take value from tempalte?

2020-11-01 15:17 UTC, yodarshafrir1 requested changes

2020-11-01 15:17 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		if err != nil && templateField.Value != "" {
Doesn't the cli need to override this value?

2020-11-02 08:28 UTC, omer-dayan commented on cmd/job/submit/submit_template_util.go
> +	defer (func() {
Its the function that translate a panic to an error in case of missing flag.

2020-11-02 08:28 UTC, omer-dayan commented on cmd/job/submit/submit_template_util.go
> +	defer (func() {
Moved to different function

2020-11-02 08:30 UTC, omer-dayan commented on cmd/job/submit/submit_template_util.go
> +	if templateField != nil {
Yes, the default template is the "templateField" in this case and its changing the required value

2020-11-02 10:23 UTC, omer-dayan commented on cmd/job/submit/submit_template_util.go
> +		if err != nil && templateField.Value != "" {
Yes it does

2020-11-02 11:36 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +	if templateField != nil {
Moshe is currently working on setting some fields as required by cobra.
Before your PR he could have used https://github.com/spf13/cobra/issues/206#issuecomment-471959800 `cobra.MarkFlagRequired()`

We can set a flag that will be required in every run, if they will not be mentioned in the template we want to fail the job.
Can you think about this case? what would be the right solution? check if the flag is required by cobra first? not use cobra to set a required fields and add checks after the templates logic?

2020-11-02 11:41 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +	defer (func() {
looks great!

2020-11-02 11:44 UTC, yodarshafrir1 requested changes

2020-11-02 11:44 UTC, yodarshafrir1 commented on cmd/job/submit/submit_template_util.go
> +		if r := recover(); r != nil {
Can you use the method  `recoverFromMissingFlag` here too

2020-11-03 11:31 UTC, merged