Omer/mege templates
run-ai/runai-cli pull request #58
Opened 2020-11-03 11:36 UTC by omer-dayan

2020-11-04 18:04 UTC, yodarshafrir1 requested changes

2020-11-04 18:04 UTC, yodarshafrir1 commented on cmd/job/submit/submit_mpi.go
> +		templateToUse, err := templates.GetSubmitTemplateFromYaml(defaultTemplate.Values)
check if null - as we spoke online

2020-11-05 06:58 UTC, omer-dayan commented on cmd/job/submit/submit_mpi.go
> +		if defaultTemplate != nil {
it uses only the user template

2020-11-05 11:23 UTC, yodarshafrir1 approved these changes

2020-11-05 11:39 UTC, merged