RUN-1233 - Assign logged in user to jobs where possible
run-ai/runai-cli pull request #77
Opened 2020-12-03 14:12 UTC by 85danf

2020-12-06 09:08 UTC, yodarshafrir1 requested changes

2020-12-06 09:08 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +			submitArgs.User = osUser.Username
why change the old logic and not use:
```
        currentUser, err := user.Current()
	if err != nil {
		defaultUser = ""
	} else {
		defaultUser = currentUser.Username
	}
```

2020-12-06 09:08 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +			submitArgs.User = osUser.Username
what happens on the first submit, when there's no token?

2020-12-07 08:50 UTC, 85danf commented on cmd/job/submit/submit.go
> +			submitArgs.User = osUser.Username
How is the new logic 
```
if osUser, err := user.Current(); err == nil {
			// Fallback to OS user
			submitArgs.User = osUser.Username
```

different from the old logic?

```
     currentUser, err := user.Current()
	if err != nil {
		defaultUser = ""
	} else {
		defaultUser = currentUser.Username
	}
```

The difference is purely semantic.


This logic relies on the permission check being run beforehand (thus populating the token as part of the check itself).
In cases where token auth is not used the user will be the OS user, like it was up until now

2020-12-08 18:19 UTC, yodarshafrir1 commented on cmd/job/submit/submit.go
> +			submitArgs.User = osUser.Username
sorry i though osUser is taken from somewhere else. ignore this comment

2020-12-08 18:21 UTC, yodarshafrir1 approved these changes

2020-12-09 11:19 UTC, merged