RUN-1229 - runai login command with oidc support
run-ai/runai-cli pull request #80
Opened 2020-12-14 21:09 UTC by 85danf

2020-12-17 15:47 UTC, yodarshafrir1 requested changes
thanks for the PR.
notes:
1. let's move the admin parameters to the admin cli.
2. let's show a proper message when the user isn't logged in and has no permissions.
3. since the user doesn't really need to provide any parameters to the login command, can we ask the user to authenticate when he fails to run a command due to not been authenticated?

2020-12-20 09:35 UTC, 85danf commented
About the general comments up top:
1. what are the 'admin' parameters? why would you deny the user a way of fixing their problems locally without having to involve an admin/runai support?
2. What exact command are you referring to? the permission check in every command already shows such a message.
3. I don't think you should instruct the user to login after every failure since it can be very frustrating if we tell them to login but it turns out they just don't have permissions (i.e. not an executor) - in this case they will login and still fail and still see the 'you should login' message which is confusing and frustrating IMO

2020-12-20 09:39 UTC, 85danf commented on cmd/login/login.go
> +func shouldDoAuth(kubeConfig *clientapi.Config) bool {
So they should not use the `login` command.. 
I have no way of verifying which of the contexts in a kubeconfig file relate to the cluster we care about (in multi-cluster kubeconfig cases).
The best we can do there is guess and I think we should not because there are a lot of edge cases to cover there and it will only cause you more work to cover all of them.

2020-12-20 09:41 UTC, 85danf commented on cmd/login/login.go
> +func getOrCreateAuthProviderConfig(kubeConfig *clientapi.Config) (authProviderConfig AuthProviderConfig, err error) {
You are really aiming for the user to be powerless in this case, I think its a huge mistake not to let users solve their own problems and instead rely on some magical admin.
If they already have the parameters (and they usually will have) why not let them fix their mistakes or misconfiguration? why make them run to the admin/support each time something doesn't work instead of explaining this with proper documentation?

2020-12-20 09:41 UTC, 85danf commented on cmd/login/login.go
> +	if paramClientSecret == "" {
You are really aiming for the user to be powerless in this case, I think its a huge mistake not to let users solve their own problems and instead rely on some magical admin.
If they already have the parameters (and they usually will have) why not let them fix their mistakes or misconfiguration? why make them run to the admin/support each time something doesn't work instead of explaining this with proper documentation?

2020-12-20 09:41 UTC, 85danf commented on cmd/login/login.go
> +		if clientId, err := util.ReadString("Client ID: "); err == nil {
You are really aiming for the user to be powerless in this case, I think its a huge mistake not to let users solve their own problems and instead rely on some magical admin.
If they already have the parameters (and they usually will have) why not let them fix their mistakes or misconfiguration? why make them run to the admin/support each time something doesn't work instead of explaining this with proper documentation?

2020-12-20 09:42 UTC, 85danf commented on cmd/login/login.go
> +	if config.IssuerUrl == DefaultIssuerUrl || config.IssuerUrl == "" {
like above

2020-12-20 09:42 UTC, 85danf commented on cmd/login/login.go
> +	if config.RedirectUrl == DefaultRedirectUrl || config.RedirectUrl == "" {
You are really aiming for the user to be powerless in this case, I think its a huge mistake not to let users solve their own problems and instead rely on some magical admin.
If they already have the parameters (and they usually will have) why not let them fix their mistakes or misconfiguration? why make them run to the admin/support each time something doesn't work instead of explaining this with proper documentation?

2020-12-20 09:45 UTC, 85danf commented on cmd/login/login.go
> +	if config.AuthRealm == "" {
Auth realm is for the auth0 password authentication that I already showed you a few times - we are required to pass it if we use the password auth flow.
currently this is the name of the connection you have in auth0 for each application.

And again, in this case - like the others, why would you not want the user to be able to fix their issues locally instead of relying on admin all of the time?  these are flags that supply the required config for being able to login and you want it to just be handed to users by the admin in a file... which is nice but you constrain yourself to exactly one usecase instead of allowing support for any usecase.

2020-12-22 08:11 UTC, yodarshafrir1 commented
In the login command, it take the current kubeconfig-user and injecting the tokens to this user. In the logout command it search for a specific user in the kubeconfig file (“runai-oidc”) and delete the tokens from this user. why not do the same like in the login command, take the current kubeconfig-user, and delete the tokens if they exists 
@85danf

2020-12-22 08:22 UTC, 85danf commented
fixed

2020-12-31 13:54 UTC, closed without merging